version: "3"
services:
  kibana:
    container_name: kibana
    image: kibana:5.6
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      - elasticsearch-kibana

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:5.6
    environment:
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data:/usr/share/elasticsearch/data 
      - ./plugins:/usr/share/elasticsearch/plugins
    networks:
      - elasticsearch-kibana


networks:
  elasticsearch-kibana:
    driver: bridge
